services:

  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: taxifares

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080

  app:
    build: ./server.py
