version: '3.8'
services:
  postgres:
    image: postgres:buster
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - database-data:/var/lib/postgresql/data

  app:
    build: ./app
    restart: always
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres

      API_HOST: "http://localhost:5000"
      API_PORT: 5000
    depends_on:
      - postgres
    ports:
      - 5000:5000
    expose:
      - 5000

  web:
    build: ./web
    environment:
      - REACT_APP_PORT=3000
    expose:
      - 3000
    restart: always
    ports:
      - '3000:3000'
    links:
      - app
  scripts:
    build: ./scripts
    restart: always
    depends_on:
      # - postgres
      - selenium

  selenium:
    image: seleniarm/standalone-chromium
    ports:
      - 4444:4444
    restart: always
    platform: linux/arm64
    environment:
      - SE_NODE_SESSION_TIMEOUT=100000000
      - SE_NODE_MAX_SESSIONS=2

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080

volumes:
  database-data:
    driver: local
