version: '3.8'
services:
  postgres:
    image: postgres:buster
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - database-data:/var/lib/postgresql/data

  app:
    build: ./app
    restart: always
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
    depends_on:
      - postgres
    ports:
      - '5000:5000'

  scripts:
    build: ./scripts
    restart: always
    depends_on:
      - postgres

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080

volumes:
  database-data:
    driver: local
